version: '3'
services:
    nginx:
        image: nginx:1.11
        container_name: mattcavanagh-nginx-staging
        ports:
            - "80"
        links:
            - php
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/usr/share/nginx/html # NGINX also needs access to serve statics
        environment:
            - VIRTUAL_HOST=staging.mattcavanagh.me
        restart: always
    php:
        image: phpdockerio/php7-fpm
        container_name: mattcavanagh-php-staging
        ports:
            - "9000"
        volumes:
            - ./:/usr/share/nginx/html
        restart: always
networks:
    default:
        external:
            name: local
