version: '3'
services:
    nginx:
        image: nginx:1.12
        ports:
            - "80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ../:/var/www/html # NGINX also needs access to serve statics
        environment:
            - VIRTUAL_HOST=dev.mattcavanagh.me
    composer:
        image: composer/composer
        volumes:
            - .:/app
        command: install
networks:
    default:
        external:
            name: local
