version: '3'
services:
    nginx:
        image: nginx:1.11
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/usr/share/nginx/html # NGINX also needs access to serve statics
        environment:
            - VIRTUAL_HOST=dev.mattcavanagh.me
    php:
        image: phpdockerio/php7-fpm
        ports:
            - "10000:9000"
        volumes:
            - ./:/usr/share/nginx/html
networks:
    default:
        external:
            name: local
