version: '2'
services:
    nginx:
        image: nginx:1.11
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/logs/nginx-errors.log:/var/log/nginx/error.log
            - ./docker/logs/nginx-access.log:/var/log/nginx/access.log
            - ./:/usr/share/nginx/html # NGINX also needs access to serve statics
    php:
        image: phpdockerio/php7-fpm
        ports:
            - "9000:9000"
        volumes:
            - ./:/usr/share/nginx/html
