version: '2'
services:
    nginx:
        image: tutum/nginx
        ports:
            - "80:80"
        links:
            - phpfpm
        volumes:
            - ./docker/nginx/default:/etc/nginx/sites-available/default
            - ./docker/nginx/default:/etc/nginx/sites-enabled/default
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

            - ./docker/logs/nginx-access.log:/var/log/nginx/access.log
            - ./docker/logs/nginx-error.log:/var/log/nginx/error.log

            - ./app:/usr/share/nginx/html # NGINX also needs access to serve statics
    phpfpm:
        image: php:fpm
        ports:
            - "9000:9000"
        volumes:
            - ./app:/usr/share/nginx/html
