---

- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/../vars.yml"
  tasks:
    - name: Install docker
      pip:
        name: docker
        state: present

    - name: Create docker network
      docker_network:
        name: mattcavanagh
        state: present

    - name: Build Base image (grab a snickers)
      docker_image:
        name: mattcavanagh:base # local image
        state: present
        source: build
        force_source: yes
        build:
          pull: no
          path: "{{ playbook_dir }}/../base"

    - name: Build Dev image
      docker_image:
        name: maelstromeous/applications
        state: present
        source: build
        tag: mattcavanagh-dev
        force_source: yes
        build:
          pull: no
          path: "{{ playbook_dir }}"

    - name: Start Dev Image
      docker_container:
        name: mattcavanagh-dev
        image: maelstromeous/applications:mattcavanagh-dev
        state: started
        restart: yes
        volumes:
          - "{{ root_dir }}/site:/var/www/html:rw"
        ports:
          - 80:80
          - 443:443
        networks:
          - name: "mattcavanagh"
        env:
          ENVIRONMENT: "development"
          VERSION: "12345"
          BASE_URL: "http://dev.mattcavanagh.me"
