version: "3"
services:
  production:
    container_name: mattcavanagh-production
    image: maelstromeous/mattcavanagh:production-latest
    restart: unless-stopped
    ports:
      - 8100:80
    environment:
      ENVIRONMENT: production
      BASE_URL: mattcavanagh.me
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  staging:
    container_name: mattcavanagh-staging
    image: maelstromeous/mattcavanagh:staging-latest
    restart: unless-stopped
    ports:
      - 8101:80
    environment:
      ENVIRONMENT: staging
      BASE_URL: staging.mattcavanagh.me
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
