---

- hosts: localhost
  vars:
    - USER: "{{ lookup('env', 'HOME') }}"
    - devdir: "{{ playbook_dir }}/.."
  tasks:
    - name: Import hosts into /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 {{ item }}"
      with_items:
        - dev.mattcavanagh.me
      become: yes

    - name: Install bash alias for easy dev work
      blockinfile:
        path: "{{ USER }}/.bash_aliases"
        marker: "# {mark} MATTCAVANAGH ANSIBLE MANAGED BLOCK #"
        block: |
          alias mattcavanagh="{{ devdir | realpath }}/"
          alias mattcavanagh-start="ansible-playbook {{ devdir | realpath }}/provisioning/dev/main.yml"
          alias mattcavanagh-stop="ansible-playbook {{ devdir | realpath }}/provisioning/dev/stop.yml"
          alias mattcavanagh-deploy-production="ansible-playbook {{ devdir | realpath }}/provisioning/production/deploy.yml --ask-vault-pass"
          alias mattcavanagh-deploy-staging="ansible-playbook {{ devdir | realpath }}/provisioning/staging/deploy.yml --ask-vault-pass"
          alias mattcavanagh-term="docker exec -it mattcavanagh-dev bash"
          alias mattcavanagh-reprovision="sudo ansible-playbook {{ devdir | realpath }}/provisioning/init.yml"