apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattcavanagh-staging
  labels:
    app: mattcavanagh-staging
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mattcavanagh-staging
  template:
    metadata:
      labels:
        app: mattcavanagh-staging
    spec:
      containers:
        - name: mattcavanagh-staging
          image: maelstromeous/applications:mattcavanagh-staging-{{ version }}
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "staging"
            - name: VERSION
              value: "{{ version }}"
            - name: BASE_URL
              value: "https://www.mattcavanagh.me"
      imagePullSecrets:
        - name: regcred