apiVersion: v1
kind: Namespace
metadata:
  name: mattcavanagh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattcavanagh-{{ environment }}
  namespace: mattcavanagh
  labels:
    app: mattcavanagh-{{ environment }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mattcavanagh-{{ environment }}
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mattcavanagh-{{ environment }}
        version: {{ version }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: mattcavanagh-{{ environment }}
      containers:
        - name: application
          image: maelstromeous/applications:mattcavanagh-{{ environment }}-{{ version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "{{ environment }}"
            - name: VERSION
              value: "{{ version }}"
            - name: BASE_URL
              value: "https://{{ hostname }}"
          resources:
            requests:
              cpu: "25m"
              memory: "32Mi"
            limits:
              cpu: "50m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mattcavanagh-{{ environment }}
  namespace: mattcavanagh
spec:
  selector:
    app: mattcavanagh-{{ environment }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
