apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattcavanagh-production
  labels:
    app: mattcavanagh-production
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: mattcavanagh-production
  template:
    metadata:
      labels:
        app: mattcavanagh-production
    spec:
      containers:
        - name: mattcavanagh-production
          image: maelstromeous/applications:mattcavanagh-production-{{ version }}
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "production"
            - name: VERSION
              value: "{{ version }}"
            - name: BASE_URL
              value: "https://mattcavanagh.me"
      imagePullSecrets:
        - name: regcred