---
- hosts: localhost
  vars_files:
    - "{{ playbook_dir }}/../../secrets.yml"
  tasks:
    - name: Create K8s Service
      k8s:
        state: present
        namespace: default
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: mattcavanagh-production
            labels:
              app: mattcavanagh-production
          spec:
            type: ClusterIP
            selector:
              app: mattcavanagh-production
            ports:
              - port: 80
                targetPort: 80

    - name: Create K8s Deployment
      k8s:
        state: present
        namespace: default
        force: yes
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: mattcavanagh-production
            labels:
              app: mattcavanagh-production
          spec:
            replicas: 1
            revisionHistoryLimit: 1
            selector:
              matchLabels:
                app: mattcavanagh-production
            template:
              metadata:
                labels:
                  app: mattcavanagh-production
              spec:
                containers:
                  - name: mattcavanagh-production
                    image: maelstromeous/applications:mattcavanagh-production-UNKNOWN
                    ports:
                      - containerPort: 80
                    env:
                      - name: ENVIRONMENT
                        value: "production"
                      - name: VERSION
                        value: "UNKNOWN"
                      - name: BASE_URL
                        value: "https://www.mattcavanagh.me"
                    resources:
                      requests:
                        memory: "32Mi"
                        cpu: "25m"
                      limits:
                        memory: "64Mi"
                        cpu: "250m"
                imagePullSecrets:
                  - name: regcred

    - name: Create K8s LetsEncrypt certificate issuer
      k8s:
        state: present
        namespace: default
        definition:
          apiVersion: cert-manager.io/v1alpha2
          kind: ClusterIssuer
          metadata:
            name: mattcavanagh-letsencrypt-production
          spec:
            acme:
              email: matt@mattcavanagh.me
              server: https://acme-v02.api.letsencrypt.org/directory
              privateKeySecretRef:
                name: mattcavanagh-letsencrypt-production
              solvers:
                - http01:
                    ingress:
                      class: nginx

    - name: Create K8s TLS Ingress using preexisting Load Balancer
      k8s:
        state: present
        namespace: default
        definition:
          apiVersion: extensions/v1beta1
          kind: Ingress
          metadata:
            name: mattcavanagh-production-ingress
            annotations:
              kubernetes.io/ingress.class: nginx
              cert-manager.io/cluster-issuer: mattcavanagh-letsencrypt-production
              nginx.ingress.kubernetes.io/proxy-body-size: 10m
          spec:
            tls:
              - hosts:
                  - mattcavanagh.me
                  - www.mattcavanagh.me
                secretName: mattcavanagh-letsencrypt-production
            rules:
              - host: mattcavanagh.me
                http:
                  paths:
                    - backend:
                        serviceName: mattcavanagh-production
                        servicePort: 80
              - host: www.mattcavanagh.me
                http:
                  paths:
                    - backend:
                        serviceName: mattcavanagh-production
                        servicePort: 80
