name: Ansible Linter
on:
  push:
    branches: [ master, staging ]
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            provisioning/production/k8s/provision-cluster.yml
            provisioning/staging/k8s/provision-cluster.yml
            provisioning/init.yml
          args: ""
