name: Build & Deploy Staging
on:
  push:
    branches: [ staging ]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

#      - name: Build base image
#        uses: docker/build-push-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#          path: provisioning/base
#          repository: maelstromeous/applications
#          tags: mattcavanagh-base

      - name: Build staging image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: maelstromeous/applications
          dockerfile: provisioning/staging/Dockerfile
          always_pull: true
          tags: mattcavanagh-staging-${{ github.sha }}

  deploy-to-k8s:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Inject the templates with the correct variables. {{ version }} refers to the Git SHA and is what changes the container version.
      - name: Update the K8s common resource file
        run: |
          sed -is -e 's|{{ version }}|${{ github.sha }}|' \
          -e 's|{{ replicas }}|1|' \
          -e 's|{{ environment }}|staging|' \
          -e 's|{{ hostname }}|staging.mattcavanagh.me|' \
          provisioning/k8s/*.yml

      # Apply the common resources, telling k8s to change the container version to the new one.
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f provisioning/k8s/common.yml

      # Apply environment specific resources
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f provisioning/k8s/staging.yml

      # Outputs the rollout status and returns a 0 signal (thus completing the workflow) once it's rolled out.
      - uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status deployment/mattcavanagh-staging -n mattcavanagh
