name: Build & Deploy Production
on:
  push:
    branches: [ master ]
jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Where am I?
        run: pwd
      - name: List files
        run: ls -lah
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: provisioning/base/Dockerfile
          repository: maelstromeous/applications
          tags: mattcavanagh-production-base
          tag_with_sha: true
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerfile: provisioning/production/Dockerfile
          repository: maelstromeous/applications
          tags: mattcavanagh-production-${{ github.sha }}
