name: Build & Deploy Production
on:
  push:
    branches: [ master ]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
  build-base-image:
    runs-on: ubuntu-latest
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        dockerfile: ../../provisioning/base/Dockerfile
        repository: maelstromeous/applications
        tags: mattcavanagh-production-base
        tag_with_sha: true
  build-production-image:
    runs-on: ubuntu-latest
    - uses: docker/build-push-action@v1
    with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
      dockerfile: ../../provisioning/base/Dockerfile
      repository: maelstromeous/applications
      tags: mattcavanagh-production-${{ github.sha }}
