name: Build & Deploy Production
on:
  push:
    branches: [ master ]
jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          path: provisioning/base
          repository: maelstromeous/applications
          tags: mattcavanagh-production-base
          tag_with_sha: true
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: maelstromeous/applications
          always_pull: true
          tags: mattcavanagh-production-${{ github.sha }}
